apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app.kubernetes.io/created-by: group1-nus
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: ui
    app.kubernetes.io/instance: ui
    app.kubernetes.io/component: service
