apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app.kubernetes.io/created-by: group1-nus
    app.kubernetes.io/type: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: ui
      app.kubernetes.io/instance: ui
      app.kubernetes.io/component: service
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8000"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: ui
        app.kubernetes.io/instance: ui
        app.kubernetes.io/component: service
        app.kubernetes.io/created-by: group1-nus
    spec:
      serviceAccountName: ui
      containers:
      - name: ui
        env:
        - name: VITE_AUTH_API_END_POINT
          value: http://auth-service-alb-d3a042cd7fba83f9.elb.ap-southeast-1.amazonaws.com/api/v1/
        - name: VITE_JOB_API_END_POINT
          value: http://ac7c6beb26f644fe780b7fc48a5d63a1-33271367384d1f3d.elb.ap-southeast-1.amazonaws.com/api/v1/
        envFrom:
        - configMapRef:
            name: ui
        image: 876708361421.dkr.ecr.ap-southeast-1.amazonaws.com/hris_frontend:v1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources: {}
      restartPolicy: Always
